[package]
name = "verwalter-minimal-wasm-scheduler"
description = """
    Demo scheduler in rust+webassembly for verwalter
"""
version = "0.1.0"

[dependencies]
serde = "1.0.0"
serde_derive = "1.0.69"
serde_json = "1.0.0"
