[package]
name = "verwalter"
description = """
    Decentralized resource and configuration management daemon
"""
readme = "README.rst"
keywords = ["cluster", "linux", "resource", "configuration", "management"]
version = "0.8.12"
homepage = "http://github.com/tailhook/verwalter"
documentation = "http://verwalter.readthedocs.org"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
rotor = "0.6.3"
rotor-http = "0.7.0"
rotor-tools = "0.3.2"
rotor-cantal = { rev="080ffac", git="git://github.com/tailhook/rotor-cantal" }
lua = "0.0.10"
argparse = "0.2"
handlebars = { version="0.26.1" }
log = "0.3.2"
env_logger = "0.3.5"
tempfile = "2.1.5"
rustc-serialize = "0.3.16"
quire = "0.2.2"
yaml-rust = "0.3"
scan_dir = "0.3"
time = "0.1.32"
rand = "0.3.11"
libc = "0.2"
matches = "0.1.2"
mio = "0.5"
nix = "0.8.0"
cbor-codec = "0.7.1"
regex = "0.2.1"
lazy_static = "0.2.6"
sha1 = "0.2.0"
inotify = "0.3.0"
itertools = "0.6.0"
gron = "0.3.0"
self-meter = "0.3.0"
quick-error = "1.1.0"
libcantal = { git="git://github.com/tailhook/cantal-rs", rev="bbe360a" }
tera = "0.10.5"
error-chain = "0.10.0"  # for tera
serde_json = "1.0.0"

[dependencies.indexed_log]
path = "./indexed_log"

[dependencies.verwalter_config]
path = "./verwalter_config"

[[bin]]
name = "verwalter"
path = "src/daemon/main.rs"

[[bin]]
name = "verwalter_render"
path = "src/render/main.rs"
